version: "3"

services:
  nginx:
    image: nginx:latest
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postservice
      - userservice
      - notificationservice

  notificationservice:
    build: ./MicroServices/NotificationService
    ports:
      - 5656:5656
    depends_on:
      - notificationdb
        # condition: service_healthy
    environment: #! use it to avoid ERRCONNECTIONREFUSED error
      - DB_URL=mongodb://notificationdb/notifydb
    volumes:
      - mongo-data-user:/data/db-user

  notificationdb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data-notification:/data/db-notification

  postservice:
    build: ./MicroServices/PostService
    ports:
      - 4646:4646
    depends_on:
      - postdb
      - minio
    environment:
      - DB_URL=mongodb://postdb/postdb
    volumes:
      - ./MicroServices/PostService:/app/post_data

  postdb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data-post:/data/db-post

  minio:
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  userservice:
    build: ./MicroServices/UserService
    ports:
      - 3636:3636
    depends_on:
      - userdb
    environment:
      - DB_URL=mongodb://userdb/userdb
    volumes:
      - mongo-data-user:/data/db-user

  userdb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data-user:/data/db-user

volumes:
  mongo-data-notification:
  mongo-data-post:
  mongo-data-user:
