version: "3"

services:
  nginx:
    image: nginx:latest
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postservice
      - userservice
      - notificationservice

  notificationservice:
    build: ./MicroServices/NotificationService
    ports:
      - 5656:5656    
    depends_on:
      - notificationdb
        # condition: service_healthy

  notificationdb:
    image: mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-data-notification:/data/db-notification

  postservice:
    build: ./MicroServices/PostService
    ports:
      - 4646:4646    
    depends_on:
      - postdb
      - minio
    # environment:
    #   - MONGO_URL="mongodb://postdb:27017/post?directConnection=true"

  postdb:
    image: mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-data-post:/data/db-post

  minio:
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  userservice:
    build: ./MicroServices/UserService
    ports:
      - 3636:3636
    depends_on:
      - userdb
    # environment:
    #   - MONGO_URL="mongodb://userdb:27017/user?directConnection=true"

  userdb:
    image: mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-data-user:/data/db-user

volumes:
  mongo-data-notification:
  mongo-data-post:
  mongo-data-user:
